### ISSUE TITLE
Your editing of tasmota hardware prep wiki page

### ISSUE THREAD

**Issue by lbdroid** [ascillato/Sonoff-Tasmota_KNX#345]
Sonoff power supplies are isolated. Just because one person managed to set one on fire by making a bad connection does not mean that there is AC on the connection header.

Please do not persist on resetting the phrase to ignorant fear mongering. If you feel like expanding on warnings about playing with AC circuits that you aren't knowledgeable about, then go right ahead, but implying that there is AC on the data header that will cause the sonoff or other connected devices to be damaged is factually wrong.

The schematics for the sonoff devices are PUBLIC, provided by itead themselves, and they show a very clear separation between the high and low voltage sides of it.

If you are still of the (incorrect) opinion that the low voltage side of the circuit is rippling with high voltage AC, then I'd suggest that you consult a competent electrical engineer to clarify.

**Comment by ascillato** [comment]
I revert your changes and add more warnings because we already had issues of people complaining about electroshocks.

There are a bunch of newbies that know nothing about AC. So, if you (lbdroid) knows what you are doing with the hardware, I congratulate you. But for most of the people "tinkering" with sonoff devices, a warning for danger MUST BE MADE. 

All the sonoffs and other brands of devices with power measurements HAVE THE MAINS AC DIRECTLY CONNECTED TO THE ESP8266, so any sensor or switch you connect WILL BE ALSO CONNECTED TO MAINS AC. 

I know, a sonoff basic have the power regulator isolated from mains, but a pow doesn't. 

So, please, don't get mad or complain about this warnings we made. We don't want any people to get electrocuted because they are tinkering without knowledge.

SAFETY FIRST.

Please, do not revert the warnings of the wiki or I will put this case to github to ban your account for unsafety and danger comments.
